// suggest-data.js — curated suggestion lists for the Vibe-tab autocomplete.
// ARTISTS drives Artist mode; VIBE_WORDS drives Vibe mode. Broad but not
// exhaustive — the fuzzy matcher tolerates partial/misspelled input, and this is
// only a spelling/lookup aid (Artist mode always decomposes the name, never
// emits it). Add freely; order doesn't matter (ranking is by match quality).

export const ARTISTS = [
  // Pop
  "Taylor Swift",
  "Beyoncé",
  "Ariana Grande",
  "Dua Lipa",
  "Billie Eilish",
  "Olivia Rodrigo",
  "Harry Styles",
  "Ed Sheeran",
  "Bruno Mars",
  "Lady Gaga",
  "Katy Perry",
  "Rihanna",
  "Justin Bieber",
  "The Weeknd",
  "Sabrina Carpenter",
  "Charli XCX",
  "Chappell Roan",
  "Lorde",
  "Sia",
  "Adele",
  "Michael Jackson",
  "Madonna",
  "Prince",
  "Whitney Houston",
  "ABBA",
  // Hip-hop / R&B
  "Kendrick Lamar",
  "Drake",
  "Kanye West",
  "Travis Scott",
  "Tyler, the Creator",
  "Frank Ocean",
  "SZA",
  "Doja Cat",
  "Nicki Minaj",
  "Cardi B",
  "J. Cole",
  "Lil Wayne",
  "Jay-Z",
  "Nas",
  "Outkast",
  "A Tribe Called Quest",
  "Lauryn Hill",
  "Erykah Badu",
  "D'Angelo",
  "Anderson .Paak",
  "Childish Gambino",
  "Mac Miller",
  "Metro Boomin",
  "Playboi Carti",
  "Doechii",
  // Rock / alt
  "The Beatles",
  "The Rolling Stones",
  "Led Zeppelin",
  "Pink Floyd",
  "Queen",
  "Nirvana",
  "Radiohead",
  "Arctic Monkeys",
  "The Strokes",
  "Tame Impala",
  "Red Hot Chili Peppers",
  "Foo Fighters",
  "Fleetwood Mac",
  "David Bowie",
  "The Cure",
  "Joy Division",
  "Talking Heads",
  "The Smiths",
  "Pixies",
  "My Bloody Valentine",
  "Nine Inch Nails",
  "Rage Against the Machine",
  "Muse",
  "The White Stripes",
  "Vampire Weekend",
  // Metal
  "Metallica",
  "Black Sabbath",
  "Slipknot",
  "Tool",
  "System of a Down",
  "Gojira",
  "Deftones",
  "Mastodon",
  "Iron Maiden",
  "Ghost",
  // Electronic / dance
  "Daft Punk",
  "Aphex Twin",
  "The Chemical Brothers",
  "Fatboy Slim",
  "Justice",
  "Disclosure",
  "Bonobo",
  "Four Tet",
  "Burial",
  "Jamie xx",
  "Flume",
  "ODESZA",
  "Skrillex",
  "Deadmau5",
  "Calvin Harris",
  "Fred again..",
  "Jon Hopkins",
  "Caribou",
  "Boards of Canada",
  "Moderat",
  "Kaytranada",
  "Peggy Gou",
  "Nicolas Jaar",
  "SBTRKT",
  "Rüfüs Du Sol",
  // Indie / folk / singer-songwriter
  "Bon Iver",
  "Sufjan Stevens",
  "Phoebe Bridgers",
  "Fleet Foxes",
  "The National",
  "Sufjan Stevens",
  "Mitski",
  "Big Thief",
  "Angel Olsen",
  "Weyes Blood",
  "Nick Drake",
  "Joni Mitchell",
  "Bob Dylan",
  "Neil Young",
  "Leonard Cohen",
  "Sufjan Stevens",
  "Iron & Wine",
  "José González",
  "Beach House",
  "Cigarettes After Sex",
  // Soul / funk / jazz
  "Stevie Wonder",
  "Marvin Gaye",
  "Aretha Franklin",
  "James Brown",
  "Curtis Mayfield",
  "Al Green",
  "Sade",
  "Amy Winehouse",
  "Nina Simone",
  "Ella Fitzgerald",
  "Miles Davis",
  "John Coltrane",
  "Herbie Hancock",
  "Kamasi Washington",
  "Robert Glasper",
  // Country / Americana
  "Johnny Cash",
  "Dolly Parton",
  "Willie Nelson",
  "Chris Stapleton",
  "Kacey Musgraves",
  "Zach Bryan",
  "Sturgill Simpson",
  "Tyler Childers",
  "Morgan Wallen",
  "Luke Combs",
  // Latin / global / K-pop
  "Bad Bunny",
  "Rosalía",
  "Karol G",
  "Rauw Alejandro",
  "Shakira",
  "BTS",
  "BLACKPINK",
  "NewJeans",
  "Stromae",
  "Burna Boy",
  "Fela Kuti",
  "Manu Chao",
  "Gipsy Kings",
  "Buena Vista Social Club",
  "Ryuichi Sakamoto",
  // Ambient / cinematic
  "Brian Eno",
  "Hans Zimmer",
  "Ludovico Einaudi",
  "Max Richter",
  "Sigur Rós",
  "Explosions in the Sky",
  "Godspeed You! Black Emperor",
  "Tycho",
  "Nils Frahm",
  "Ólafur Arnalds",
];

export const VIBE_WORDS = [
  // Feelings / mood
  "melancholy",
  "euphoric",
  "dreamy",
  "nostalgic",
  "hypnotic",
  "brooding",
  "uplifting",
  "sultry",
  "aggressive",
  "gentle",
  "haunting",
  "playful",
  "cinematic",
  "romantic",
  "anthemic",
  "eerie",
  "warm",
  "cold",
  "triumphant",
  "wistful",
  "defiant",
  "serene",
  "frantic",
  "sensual",
  "bittersweet",
  // Textures / production
  "lo-fi",
  "hi-fi",
  "analog warmth",
  "gated reverb",
  "shimmering",
  "gritty",
  "washed-out",
  "punchy",
  "spacious",
  "minimal",
  "lush",
  "distorted",
  "glitchy",
  "cinematic strings",
  "vinyl crackle",
  "tape saturation",
  "reverb-drenched",
  // Genres
  "synthwave",
  "vaporwave",
  "dream pop",
  "shoegaze",
  "bedroom pop",
  "indie folk",
  "trip-hop",
  "neo-soul",
  "boom bap",
  "trap",
  "drill",
  "house",
  "deep house",
  "techno",
  "ambient",
  "drum and bass",
  "garage",
  "afrobeats",
  "reggaeton",
  "bossa nova",
  "jazz fusion",
  "post-rock",
  "math rock",
  "grunge",
  "britpop",
  "city pop",
  "hyperpop",
  "phonk",
  "future funk",
  "downtempo",
  "chillwave",
  // Scenes / settings
  "late night drive",
  "rainy window",
  "sunrise beach",
  "neon city",
  "empty highway",
  "campfire",
  "dive bar",
  "rooftop party",
  "long train ride",
  "snowy morning",
];
